server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OHYONGSU/p_config.git
          search-paths: '{application}/{profile}, infra/host/{profile}, infra/{profile}'


